@base_url = http://localhost:8081/api/v1/auth

###
POST {{base_url}}/register
Content-Type: application/json

{
  "username": "educator1",
  "firstName": "educator-first-name",
  "lastName": "educator-last-name",
  "email": "educator1@mail.com",
  "password": "password",
  "birthDate": "2000-01-01"
}

###
# @name auth
POST http://localhost:8080/realms/ora/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=john.doe@example.com&password=StrongPassword123!&grant_type=password&client_id=auth-service&scope=openid

### Get Admin Token
# @name auth
POST http://localhost:8080/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli&username=admin&password=admin&grant_type=password

### Get User Details
GET http://localhost:8080/admin/realms/ora/users?username=john_doe
Authorization: Bearer {{auth.response.body.access_token}}