from enum import Enum


class ErrorCode(str, Enum):
    INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER"
    MODEL_VALIDATION = "ERROR_MODEL_VALIDATION"
    INVALID_TOKEN = "ERROR_TOKEN_INVALID"
    UNAUTHORIZED = "ERROR_UNAUTHORIZED"
    PRODUCT_CANNOT_BE_PURCHASED = "ERROR_PRODUCT_CANNOT_BE_PURCHASED"
