from enum import Enum


class ErrorCode(str, Enum):
    ERROR_INTERNAL_SERVER = "ERROR_INTERNAL_SERVER"
    ERROR_MODEL_VALIDATION = "ERROR_MODEL_VALIDATION"
    ERROR_TOKEN_INVALID = "ERROR_TOKEN_INVALID"
    ERROR_PUBLIC_KEY_FETCH = "ERROR_PUBLIC_KEY_FETCH"
    ERROR_KEYS_EXPIRED = "ERROR_KEYS_EXPIRED"
    ERROR_AUTHORIZATION_FAILED = "ERROR_AUTHORIZATION_FAILED"
