server:
  port: "${PROFILE_PORT}"
  name: "${PROFILE_NAME:-profile-service}"

spring:
  datasource:
    url: "${PROFILE_DB_URL}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${KEYCLOAK_JWKS_URI}"
          issuer: "${KEYCLOAK_ISSUER_URI}"
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USER}"
    password: "${RABBITMQ_PASS}"
    virtual-host: "${RABBITMQ_VHOST}"
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0
          max-attempts: 3
        default-requeue-rejected: false
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-methods: ${ALLOWED_METHODS}
    allowed-headers: ${ALLOWED_HEADERS}
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:user-service-exchange}
    dlq-exchange: ${RABBITMQ_DLQ_EXCHANGE:dead-letter-exchange}
    message-ttl: ${RABBITMQ_MESSAGE_TTL:30000}
  otel:
    serviceName: "${PROFILE_NAME:-profile-service}"
    endpoint: "${OTEL_GRPC_URL:-http://localhost:4317}"
    enableTraces: "${PROFILE_OTEL_TRACING:true}"
    enableMetrics: "${PROFILE_OTEL_METRICS:true}"
    enableLogs: "${PROFILE_OTEL_LOGGING:true}"