@schedule_base_url = http://localhost:8084/api/v1/schedules
@booking_base_url = http://localhost:8084/api/v1/bookings

###
# @name auth
POST http://localhost:8080/realms/coursio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=teacher1@mail.com&password=password&grant_type=password&client_id=scheduling-service&scope=openid

###
GET {{schedule_base_url}}/76df65b1-0919-4d7b-9b82-4c58b27ad578/schedule?fromDate=2025-01-11&toDate=2025-01-15
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{schedule_base_url}}/working-periods
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "date": "2025-01-13",
  "startTime": "10:00:00",
  "endTime": "17:00:00"
}

###
PUT {{schedule_base_url}}/working-periods/2
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "date": "2025-01-14",
  "startTime": "10:00:00",
  "endTime": "16:00:00"
}

###
DELETE {{schedule_base_url}}/working-periods/2
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{schedule_base_url}}/working-periods/1/events
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "sessionId": 1,
  "startTime": "10:00:00",
  "endTime": "11:00:00",
  "maxParticipants": 4
}

###
DELETE {{schedule_base_url}}/events/{id}
Authorization: Bearer {{auth.response.body.access_token}}


###
POST {{booking_base_url}}
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
	"teacherId": "76df65b1-0919-4d7b-9b82-4c58b27ad578",
	"sessionId": 1,
	"scheduledEventId": null,
	"workingPeriodId":  1,
  "startTime": "10:00:00",
  "endTime": "11:00:00",
}

###
POST {{booking_base_url}}/{id}/status/{status}
Authorization: Bearer {{auth.response.body.access_token}}