@session_base_url = http://localhost:8083/api/v1/sessions
@enrollment_base_url = http://localhost:8083/api/v1/enrollments

###
# @name auth
POST http://localhost:8080/realms/coursio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=teacher1@mail.com&password=password&grant_type=password&client_id=learning-service&scope=openid

###
GET {{session_base_url}}/my?skip=0&take=10
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{session_base_url}}/1
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{session_base_url}}
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "title": "software-engineering",
  "description": "software engineering session",
  "type": 0,
  "options": [ { "duration": 60 } ]
}

###
PUT {{session_base_url}}/1
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "title": null,
  "description": "software engineering session",
  "type": 2,
  "options": [ { "duration": 60 } ]
}

###
POST {{enrollment_base_url}}/1
Authorization: Bearer {{auth.response.body.access_token}}