server:
  port: "${AUTH_PORT}"

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USER}"
    password: "${RABBITMQ_PASS}"
    virtual-host: "${RABBITMQ_VHOST}"
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0
          max-attempts: 3
        default-requeue-rejected: false
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
  
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-methods: ${ALLOWED_METHODS}
    allowed-headers: ${ALLOWED_HEADERS}
  keycloak:
    url: "${KEYCLOAK_URL}"
    realm: "${KEYCLOAK_REALM}"
    clientId: "${KEYCLOAK_AUTH_CLIENT_ID}"
    clientSecret: "${KEYCLOAK_AUTH_CLIENT_SECRET}"
    adminClientId: "${KEYCLOAK_ADMIN_CLIENT_ID}"
    adminUsername: "${KEYCLOAK_ADMIN_USER}"
    adminPassword: "${KEYCLOAK_ADMIN_PASSWORD}"
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:user-service-exchange}
    dlq-exchange: ${RABBITMQ_DLQ_EXCHANGE:dead-letter-exchange}
    message-ttl: ${RABBITMQ_MESSAGE_TTL:30000}